### ISSUE TITLE
"Permission denied" on Linux

### ISSUE THREAD

**Issue by l0b0** [techiew/EldenRingModLoader#8]
```
$ er-patcher -c -v -s -- %command%
/etc/profiles/per-user/username/bin/er-patcher:133: DeprecationWarning: pathlib.Path.link_to() is deprecated and is scheduled for removal in Python 3.12. Use pathlib.Path.hardlink_to() instead.
  f.link_to(game_dir_patched / f)
Traceback (most recent call last):
  File "/etc/profiles/per-user/username/bin/er-patcher", line 138, in <module>
    subprocess.run(steam_cmd, cwd=steam_cmd[-1].parent.absolute())
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/mnt/foo/SteamLibrary/steamapps/common/ELDEN RING/Game/er-patcher-tmp/eldenring.exe')
```

`chmod u+x er-patcher-tmp/eldenring.exe` resulted in a different error:

```
$ er-patcher -c -v -s -- %command%
/etc/profiles/per-user/username/bin/er-patcher:133: DeprecationWarning: pathlib.Path.link_to() is deprecated and is scheduled for removal in Python 3.12. Use pathlib.Path.hardlink_to() instead.
  f.link_to(game_dir_patched / f)
Traceback (most recent call last):
  File "/etc/profiles/per-user/username/bin/er-patcher", line 138, in <module>
    subprocess.run(steam_cmd, cwd=steam_cmd[-1].parent.absolute())
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('/mnt/foo/SteamLibrary/steamapps/common/ELDEN RING/Game/er-patcher-tmp/eldenring.exe')
```

I've also tried a few more things, like `chmod a+x dinput8.dll eldenring.exe` and [`er-patcher --all -- env WINEDLLOVERRIDES="dinput8.dll=n,b" %command%`](https://github.com/techiew/EldenRingModLoader/issues/3#issuecomment-1137311151).

**Comment by l0b0** [comment]
Update: Sorry, wrong repo!
